services:
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
  
  database:
    image: mysql:latest
    container_name: mwdb
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpw
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    
  web:
    image: mystiick/mystiickweb:0.3.1
    container_name: mystiickweb
    environment:
      ConnectionStrings__ImageDatabase: server=mwdb;userid=root;password=mysqlpw;database=mystiick
      Logging__File__Path: /app/logs/mystiickweb.log
    ports:
      - 7080:80
    volumes:
      - ./samples:/img/
      - ./logs:/app/logs/

volumes:
  data: