services:
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080      
  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpw
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql

volumes:
  data: